unique_ids:
  assets:
    standard-page.html: DPIATTLUU7LETI3BAXE5LR3D52DMQODU
    theme.css: 6X5CJ7UQMDQZ5P4CGZETJ25226EVXB32
  forms:
    Form1: D2TCEOQNGTXMVFP5F2WI67NP5YMMRRPW
  modules: {}
  scripts: {}
  server_modules: {}
